server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: false # https://vladmihalcea.com/the-hibernate-enable_lazy_load_no_trans-anti-pattern/
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
        jdbc:
          #https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple?rq=1
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          query.timeout: 10000
    show-sql: true
  datasource:
    url: ${CHALLENGE_DATABASE_URL:jdbc:postgresql://localhost:54321/dota_challenge_db}
    username: ${CHALLENGE_DATABASE_USERNAME:developer}
    password: ${CHALLENGE_DATABASE_PASSWORD:password}
  flyway:
    enabled: true
    baseline-version: 1
    encoding: UTF-8
    validate-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1
  h2:
    console:
      enabled: true

logging:
  config: classpath:logback-${ENV:development}.xml
