version: '3.0'

services:
  postgres-dev-dota:
    image: postgres:12.3-alpine
    ports:
      - 54321:5432
    env_file: db.env
    networks:
      - dota-challenge-net

networks:
  dota-challenge-net:
    driver: bridge
